version: 2
jobs:
  build:
    working_directory: ~/CouncilTag-Django
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: depsx-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            # pipenv run "pip install -r requirements.txt"
      - save_cache:
          key: depsx-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
  deploy:
    machine: 
      enabled: true
    steps:
      - add_ssh_keys:
            fingerprints:
              - "90:67:7a:e6:e2:67:33:79:93:cc:6e:ec:38:fe:f5:1d"
      - run:
            name: Deploy over SSH
            command: |
                ssh $SSH_USER@$SSH_HOST "./deploy.sh"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master